[package]
name = "roadrunner"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["."]

[dependencies]
anyhow = "1.0.98"
rstest = "0.26.1"
rustyline = "17.0.0"
tracing = "0.1.41"
tracing-test = "0.2.5"
tracing-subscriber = "0.3.16"
tracing-appender = "0.2.3"
